### ISSUE TITLE
missing demo.css file

### ISSUE THREAD

**Issue by xferguson** [esterpantaleo/etymology#11]
There is a 404 error in the browser from a
`GET /resources/css/demo.css `
coming from [index.html](https://github.com/esterpantaleo/etymology/resources/html/index.html) line 5 `<link rel="stylesheet" href="../css/demo.css">`

Is that file supposed to be there, or is that line supposed to be removed?

**Comment by esterpantaleo** [comment]
Right! Just fixed this! Thanks!
