### ISSUE TITLE
function naming and potential overwrite

### ISSUE THREAD

**Issue by xferguson** [esterpantaleo/etymology#17]
it looks like we have the same `function get()` definition twice:

The first time is in the dagre-d3.js library, line 14764 (ish)
Then again in load.js, at the bottom

This is probably leading to unintended side-effects, and we should change the load.js function name. Etytree calls the function to assign the return value to `const source`.

**Comment by esterpantaleo** [comment]
how about I rename function get "getXMLHttpRequest"?

**Comment by xferguson** [comment]
That sounds reasonable. I might recommend merging pull request #18 first, as it has the lint information in place for the `get` function.
